### ISSUE TITLE
Geocoding updates

### ISSUE THREAD

**Issue by danvk** [danvk/oldnyc#150]
Things to do:

- [x] Set up truth data and evaluation system: #151 
- [x] Pull in CSV data updates from the past 12 years
- [x] Investigate "subjects" for POI geocoding: #156 
- [x] Investigate OldTO-style geocoding: #162 and #163 
- [x] Investigate GPT-based geocoding
